//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveAzure.Resources.Models.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelEnum {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelEnum() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveAzure.Resources.Models.Common.ModelEnum", typeof(ModelEnum).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://hanadev.shuanglin.com:8000/sap/opu/odata/sap/ZDM_M001_Q002_SRV/ZDM_M001_Q002{0}Results?|Title(0_0)testbar|SubTitle(0_0)subtestbar|SeriesStr(0_0)A00O2TFKZNC7K2N5JLDC443B56,A00O2TFKZNC7K2N5JLDC443NSA|AxisDataStr(0_0)A0CALMONTH|LegendDataStr(0_0)实际,预测 的本地化字符串。
        /// </summary>
        public static string Bar1 {
            get {
                return ResourceManager.GetString("Bar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0001_SRV/ZCA_M001_Q0001Results?ZINDICATR eq &apos;C0107004&apos;&amp;$select=A00O2TFHXIFF1Z930ZZCA6AK1E,A00O2TFHXIFF1Z932YMOYVZJ5H,A00O2TFHXIFF1Z931LL9MVUFR2,A0CALMONTH2&amp; Top=5|Title(0_0)采购金额月度趋势分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF1Z930ZZCA6AK1E,A00O2TFHXIFF1Z932YMOYVZJ5H,A00O2TFHXIFF1Z931LL9MVUFR2|AxisDataStr(0_0)A0CALMONTH2|LegendDataStr(0_0)实际,预算,同期 的本地化字符串。
        /// </summary>
        public static string barZCA_M001_Q0001 {
            get {
                return ResourceManager.GetString("barZCA_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0002_SRV/ZCA_M001_Q0002{0}Results?|Title(0_0)存货周转天数|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PKQ6YX4O2ZPJJ,A00O2TFHXIFF3PKQ6YX4O2ZVV3,A00O2TFHXIFF3PKQ6YX4O3026N|AxisDataStr(0_0)A0CALMONTH2|LegendDataStr(0_0)实际天数，预算天数，同期天数 的本地化字符串。
        /// </summary>
        public static string BarZCA_M001_Q0002 {
            get {
                return ResourceManager.GetString("BarZCA_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0003_SRV/ZCA_M001_Q0003{0}Results?|Title(0_0)产品成本月度趋势状况|SubTitle(0_0)subtestbar|SeriesStr(0_0)A00O2TFHXIFF3PL8NINK0A4FFL，A00O2TFHXIFF3PL8NINK0A4LR5，A00O2TFHXIFF3PLMCBWGKDDFWP，A00O2TFHXIFF3PLMBCWBWCXGM7|AxisDataStr(0_0)A0CALMONTH2|LegendDataStr(0_0)本期成本,预算成本，标准成本，上年同期金额 的本地化字符串。
        /// </summary>
        public static string barZCA_M001_Q0003 {
            get {
                return ResourceManager.GetString("barZCA_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_P001_Q0002_SRV/ZFI_P002_Q0001{0}Results?|Title(0_0)产品成本月度趋势状况SubTitle(0_0)subtestbar|SeriesStr(0_0)A00O2TFHXIFF1ZCD5XVIVC3DDI，A00O2TFHXIFF1ZCD5XVIVC371Y，A00O2TFHXIFF1ZCD5XVIVC3JP2|AxisDataStr(0_0)A0CALMONTH2|LegendDataStr(0_0)本期成本，标准成本，上年同期金额 的本地化字符串。
        /// </summary>
        public static string BarZFI_P001_Q0002 {
            get {
                return ResourceManager.GetString("BarZFI_P001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0005_SRV/ZMM_M001_Q0005{0}Results?|Title(0_0)库存呆滞状况分析|SubTitle(0_0)subtestbar|SeriesStr(0_0)A00O2TFHXIFF1ZAA3BD18ZDI2A，A00O2TFHXIFF3PKN6FN2VEPWTM，A00O2TFHXIFF3PKN6FN2VEPQI2|AxisDataStr(0_0)A0CALMONTH2|LegendDataStr(0_0)呆滞金额,上年同期呆滞率，同期呆滞率 的本地化字符串。
        /// </summary>
        public static string BarZMM_M001_Q0005 {
            get {
                return ResourceManager.GetString("BarZMM_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0004_SRV/ZMM_M002_Q0004{0}Results?|Title(0_0)年度物流费用变动趋势|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PKQS061DZ6L8J,A00O2TFHXIFF1ZAAGGZH5RU5AM,A00O2TFHXIFF1ZAAGGZH5RTYZ2|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0) 的本地化字符串。
        /// </summary>
        public static string BarZMM_M002_Q0004 {
            get {
                return ResourceManager.GetString("BarZMM_M002_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0002_SRV/ZPU_M001_Q0002{0}Results?|Title(0_0)采购金额月度趋势分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF1Z9LAXSLCIHXPA,A00O2TFHXIFF1Z9LAXSLCII40U|AxisDataStr(0_0)A0CALMONTH|LegendDataStr(0_0)A00O2TFHXIFF1Z9LAXSLCIHXPA,A00O2TFHXIFF1Z9LAXSLCII40U 的本地化字符串。
        /// </summary>
        public static string BarZPU_M001_Q0002 {
            get {
                return ResourceManager.GetString("BarZPU_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0002_SRV/ZSD_M001_Q0002{0}Results?|Title(0_0)年度销售状况分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF1Z93JUUJWHD4L2,A00O2TFHXIFF1Z93JUUJWHDAWM,A00O2TFHXIFF1Z93JUUJWHDTVA|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0)本月销售,本月目标,上年同期 的本地化字符串。
        /// </summary>
        public static string BarZSD_M001_Q0002 {
            get {
                return ResourceManager.GetString("BarZSD_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0003_SRV/ZSD_M001_Q0003{0}Results?|Title(0_0)年度销售状况分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF1Z93KU0PY37D8X_F|AxisDataStr(0_0)A0CALYEAR|LegendDataStr(0_0) 的本地化字符串。
        /// </summary>
        public static string BarZSD_M001_Q0003 {
            get {
                return ResourceManager.GetString("BarZSD_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0008_SRV/ZSD_M002_Q0008{0}Results?|Title(0_0)年度订单达交率趋势状况|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF1ZAOCVBPYC3G1M,A00O2TFHXIFF1ZAOCVBPYC3MD6,A00O2TFHXIFF1ZAOCVBPYC3SOQ|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0) 的本地化字符串。
        /// </summary>
        public static string BarZSD_M002_Q0008 {
            get {
                return ResourceManager.GetString("BarZSD_M002_Q0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://hanadev.shuanglin.com:8000/sap/opu/odata/sap/ZDM_M001_Q002_SRV/ZDM_M001_Q002{0}Results?|Title(0_0)test|SubTitle(0_0)subtest|PieMapSelectName(0_0)ZDMPLANT_T|PieMapSelectValue(0_0)A00O2TFKZNC7K2N5JLDC4434TM 的本地化字符串。
        /// </summary>
        public static string Pie1 {
            get {
                return ResourceManager.GetString("Pie1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/ZFI_M001_Q0003{0}Results?|Title(0_0)test|SubTitle(0_0)subtest|PieMapSelectName(0_0)ZPROFTCTR__ZBU_T|PieMapSelectValue(0_0)A00O2TFHXIFF3PJJNMJX09XV3R|SeriesName(0_0)test 的本地化字符串。
        /// </summary>
        public static string Pie2 {
            get {
                return ResourceManager.GetString("Pie2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0006_SRV/ZMM_M001_Q0006{0}Results?|Title(0_0)月度库存占比结构|SubTitle(0_0)|PieMapSelectName(0_0)ZMATPTYPE_T|PieMapSelectValue(0_0)A00O2TFHXIFF1ZAAFQYU1044QJ|SeriesName(0_0)存货类别 的本地化字符串。
        /// </summary>
        public static string pieZMM_M001_Q0006 {
            get {
                return ResourceManager.GetString("pieZMM_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0003_SRV/ZPU_M001_Q0003{0}Results?|Title(0_0)各类别材料采购占比|SubTitle(0_0)|PieMapSelectName(0_0)A0MATL_GROUP|PieMapSelectValue(0_0)A00O2TFHXIFF1Z9LDOWFPYMB7E|SeriesName(0_0)采购金额 的本地化字符串。
        /// </summary>
        public static string PieZPU_M001_Q0002 {
            get {
                return ResourceManager.GetString("PieZPU_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0009_SRV/ZSD_M002_Q0009{0}Results?|Title(0_0)订单延误原因分析|SubTitle(0_0)|PieMapSelectName(0_0)ZDEREASON|PieMapSelectValue(0_0)A00O2TFHXIFF1ZAOFMS03R8VNL|SeriesName(0_0) 的本地化字符串。
        /// </summary>
        public static string PieZSD_M002_Q0009 {
            get {
                return ResourceManager.GetString("PieZSD_M002_Q0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)日历年月(单值必输,默认本月)|TextField(0_0)ZMONHT003_PText|ValueField(0_0)ZMONHT003_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MText|Valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Sel1 {
            get {
                return ResourceManager.GetString("Sel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0003_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0003_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0003_SRV/|Label(0_0)利润中心(多值,可选)|TextField(0_0)ZPROFTCTR001_MMText| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZCA_M001_Q0003 {
            get {
                return ResourceManager.GetString("SelZCA_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0004_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0004_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0004_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZCA_M001_Q0004 {
            get {
                return ResourceManager.GetString("SelZCA_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0001_SRV/|Label(0_0)日历日(单值必输,默认当前一天)|TextField(0_0)ZDAY001_PMText|ValueField(0_0)ZDAY001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0001_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0001_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText|Valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0001 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)日历年月(单值必输,默认本月)|TextField(0_0)ZMONHT003_PMText|ValueField(0_0)ZMONHT003_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText|V [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0003 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0005_SRV/|Label(0_0)日历日(单值必输,默认当前一天)|TextField(0_0)ZDAY001_PText|ValueField(0_0)ZDAY001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0005_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_M_TEXT|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0005_SRV/|Label(0_0)工厂(多值,可选)|TextField(0_0)ZPLANT_TText|ValueField(0_0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0005 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0006_SRV/|Label(0_0)日历年月(单值必输,默认本月)|TextField(0_0)ZMONHT003_PMText|ValueField(0_0)ZMONHT003_P|Width(0_0)200|Multiple(0_0)true* 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0006 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0008_SRV/|Label(0_0)日历日(单值必输,默认当前一天)|TextField(0_0)ZDAY001_PMText|ValueField(0_0)ZDAY001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0008_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0008_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText|Valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0008 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0011_SRV/|Label(0_0)日历日(单值必输,默认当前一天)|TextField(0_0)ZDAY001_PMText|ValueField(0_0)ZDAY001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0011_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0011_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText|Valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0011 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0012_SRV/|Label(0_0)日历年月(单值必输,默认本月)|TextField(0_0)ZMONHT003_PMText|ValueField(0_0)ZMONHT003_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0012_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0012_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText|V [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0012 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0013_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0013_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0013_SRV/|Label(0_0)公司代码(多值,可选)|TextField(0_0)ZCOMPCODE001_MMText| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0013 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0014_SRV/|Label(0_0)日历年月(区间必输,默认本年)|TextField(0_0)ZMONTH004_IMText|ValueField(0_0)ZMONTH004_I|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0014_SRV/|Label(0_0)日历年月(区间必输,默认本年)|TextField(0_0)ZMONTH004_IToMText|ValueField(0_0)ZMONTH004_ITo|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0014_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_M001_Q0014 {
            get {
                return ResourceManager.GetString("SelZFI_M001_Q0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_P001_Q0001_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_P001_Q0001_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_P001_Q0001_SRV/|Label(0_0)工厂(多值,可选)|TextField(0_0)ZPLANT001_MMText|Value [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZFI_P001_Q0001 {
            get {
                return ResourceManager.GetString("SelZFI_P001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0004_SRV/|Label(0_0)日历日(单值必输,默认当前一天)|TextField(0_0)ZDAY001_PMText|ValueField(0_0)ZDAY001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0004_SRV/|Label(0_0)工厂(多值,可选)|TextField(0_0)ZPLANT001_MMText|ValueField(0_0)ZPLANT001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0004_SRV/|Label(0_0)物料(多值,可选)|TextField(0_0)ZMATER001_MMText|Valu [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZMM_M001_Q0004 {
            get {
                return ResourceManager.GetString("SelZMM_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0005_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0005_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0005_SRV/|Label(0_0)利润中心(多值,可选)|TextField(0_0)ZPROFTCTR001_MMText| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZMM_M001_Q0005 {
            get {
                return ResourceManager.GetString("SelZMM_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0006_SRV/|Label(0_0)日历年/月(单值必输,默认上月)|TextField(0_0)ZMONTH001_PMText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0006_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU001_MMText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0006_SRV/|Label(0_0)利润中心(多值,可选)|TextField(0_0)ZPROFTCTR001_MMText| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZMM_M001_Q0006 {
            get {
                return ResourceManager.GetString("SelZMM_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0001_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH002_IText|ValueField(0_0)ZMONTH002_I|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0001_SRV/|Label(0_0)事业部|TextField(0_0)ZBU001_MText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0001_SRV/|Label(0_0)工厂|TextField(0_0)ZPLANT001_MText|ValueField(0_0)ZPLANT001_M|Width( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZMM_M002_Q0001 {
            get {
                return ResourceManager.GetString("SelZMM_M002_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0004_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH001_PText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0004_SRV/|Label(0_0)事业部|TextField(0_0)ZBU001_MText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0004_SRV/|Label(0_0)工厂|TextField(0_0)ZPLANT001_MText|ValueField(0_0)ZPLANT001_M|Width( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZMM_M002_Q0004 {
            get {
                return ResourceManager.GetString("SelZMM_M002_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0002_SRV/|Label(0_0)日历年/月(区间必输,默认上月)|TextField(0_0)ZMONTH002_IMText|ValueField(0_0)ZMONTH002_I|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0002_SRV/|Label(0_0)日历年/月(区间必输,默认上月)|TextField(0_0)ZMONTH002_IToMText|ValueField(0_0)ZMONTH002_ITo|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0002_SRV/|Label(0_0)事业部(多值,可选)|TextField(0_0)ZBU00 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZPU_M001_Q0001 {
            get {
                return ResourceManager.GetString("SelZPU_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0004_SRV/|Label(0_0)事业部|TextField(0_0)ZBU001_MText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0004_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH002_IText|ValueField(0_0)ZMONTH002_I|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0004_SRV/|Label(0_0)工厂|TextField(0_0)ZPLANT001_MText|ValueField(0_0)ZPLANT001_M|Width( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZPU_M001_Q0004 {
            get {
                return ResourceManager.GetString("SelZPU_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0006_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH001_PText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0006_SRV/|Label(0_0)事业部|TextField(0_0)ZBU001_MText|ValueField(0_0)ZBU001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0006_SRV/|Label(0_0)工厂|TextField(0_0)ZPLANT001_MText|ValueField(0_0)ZPLANT001_M|Width( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZPU_M001_Q0006 {
            get {
                return ResourceManager.GetString("SelZPU_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0008_SRV/|Label(0_0)日历年月|TextField(0_0)ZMONHT003_PText|ValueField(0_0)ZMONHT003_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)|Label(0_0)项目类型|TextField(0_0)ZPROGTYPE001_MText|ValueField(0_0)ZPROGTYPE001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)|Label(0_0)物料组|TextField(0_0)ZMATLGROUP001_MText|ValueField(0_0)ZMATLGROUP001_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)|Label(0_0)项目|TextField(0_0)ZEINR001_MText|ValueField(0_0)ZEINR001_M|Width(0_0)200| [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZSD_M001_Q0008 {
            get {
                return ResourceManager.GetString("SelZSD_M001_Q0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0011_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH001_PText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0011_SRV/|Label(0_0)客户经理|TextField(0_0)ZEMPLOYEE002_MText|ValueField(0_0)ZEMPLOYEE002_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0011_SRV/|Label(0_0)客户|TextField(0_0)ZCUST001_MText|ValueField(0_0)ZCUST0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZSD_M001_Q0011 {
            get {
                return ResourceManager.GetString("SelZSD_M001_Q0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0008_SRV/|Label(0_0)日历年/月|TextField(0_0)ZMONTH001_PText|ValueField(0_0)ZMONTH001_P|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0008_SRV/|Label(0_0)员工|TextField(0_0)ZEMPLOYEE002_MText|ValueField(0_0)ZEMPLOYEE002_M|Width(0_0)200|Multiple(0_0)true*Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0008_SRV/|Label(0_0)客户|TextField(0_0)ZCUST001_MText|ValueField(0_0)ZCUST001 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SelZSD_M002_Q0006 {
            get {
                return ResourceManager.GetString("SelZSD_M002_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/ZFI_M001_Q0003{0}Results?|Title(0_0)到期回款状况：|FrozenColumns(0_0)[[{field: &apos;ZCUSTOMER_T&apos;,title: &apos;客户&apos;,sortable:true, formatter:&apos;&apos;,fixed:true}]]|Columns(0_0)[[{ title: &apos;Item Details&apos;, colspan: 7 }], [{ field: &apos;A00O2TFHXIFF3PJIBEFO12Z9IL_F&apos;,  title: &apos;本月到期款-原币&apos;, sortable: true, fixed: true, align: &apos;right&apos; },{ field: &apos;A00O2TFHXIFF3PJJAN433USWUC_F&apos;,   title: &apos;本月到期款-本币&apos;, sortable: true, fixed: true, align: &apos;right&apos; },{ field: &apos;A00O2TFHXIFF3PJ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tab1 {
            get {
                return ResourceManager.GetString("Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0001_SRV/$metadata?|Title(0_0)testbar 的本地化字符串。
        /// </summary>
        public static string Tab2 {
            get {
                return ResourceManager.GetString("Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0001_SRV/$metadata?|Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0001_SRV/ZCA_M001_Q0001Results?|Title(0_0)应收账款周转天数分析 的本地化字符串。
        /// </summary>
        public static string TabZCA_M001_Q0001 {
            get {
                return ResourceManager.GetString("TabZCA_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0002_SRV/ZCA_M001_Q0002{0}Results?|Title(0_0)存货周转天数|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZCA_M001_Q0002 {
            get {
                return ResourceManager.GetString("TabZCA_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0003_SRV/ZCA_M001_Q0003{0}Results?|Title(0_0)分析内容|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZCA_M001_Q0003 {
            get {
                return ResourceManager.GetString("TabZCA_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0004_SRV/ZCA_M001_Q0004{0}Results?|Title(0_0)汇总损益状况：|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZCA_M001_Q0004 {
            get {
                return ResourceManager.GetString("TabZCA_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZCA_M001_Q0005_SRV/ZCA_M001_Q0005{0}Results?|Title(0_0)明细损益状况：|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZCA_M001_Q0005 {
            get {
                return ResourceManager.GetString("TabZCA_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0001_SRV/ZFI_M001_Q0001{0}Results?|Title(0_0)总体状况概览|FrozenColumns(0_0)|Columns(0_0)
        ///[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;, title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},
        ///{ field: &apos;ZPLANT_T&apos;,   title: &apos;工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},
        ///{ field: &apos;A0DOC_CURRCY_T&apos;,   title: &apos;货币&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title: &apos;期末余额&apos;,colspan:11},
        ///{field: &apos;A00O2TFHXIFF1Z9LHQCOIQ581M_F&apos;,   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0001 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0002_SRV/ZFI_M001_Q0002{0}Results?|Title(0_0)按欠款方期末余额前五名的应收排行|FrozenColumns(0_0)|Columns(0_0)
        ///[[{field: &apos;ZCUSTOMER_T&apos;,title: &apos;单位名称&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title: &apos;期末余额&apos;,colspan:3}],
        ///[{field: &apos;A00O2TFHXIFF1Z9355BIZYES2F_F&apos;, title: &apos;应收账款&apos;, sortable: true, fixed: true, align: &apos;right&apos; },
        ///{field: &apos;A00O2TFHXIFF1Z935F4B13NOOH_F&apos;,title: &apos;占应收账款合计数的比例（%）&apos;, sortable: true, fixed: true, align: &apos;right&apos; },
        ///{field: &apos;A0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0002 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0003_SRV/ZFI_M001_Q0003{0}Results?|Title(0_0)到期回款状况|FrozenColumns(0_0)|Columns(0_0)
        ///[[{field: &apos;ZPROFTCTR__ZBU_T&apos;,title: &apos;事业部&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2},{field: &apos;ZPLANT_T&apos;,title: &apos;工厂&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2}，
        ///{field: &apos;ZCUSTOMER&apos;,title: &apos;客户编号&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2}，{field: &apos;ZCUSTOMER_T&apos;,title: &apos;客户&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2}, 
        ///{fiel [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0003 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0004_SRV/ZFI_M001_Q0004{0}Results?|Title(0_0)应收账龄与逾期状况|FrozenColumns(0_0)|Columns(0_0)
        ///[
        ///[{field: &apos;ZPROFTCTR__ZBU_T&apos;,title: &apos;事业部&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:3},{field: &apos;ZPLANT_T&apos;,title: &apos;工厂&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:3}，
        ///{field: &apos;ZCUSTOMER_T&apos;,title: &apos;客户&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:3}, {title: &apos;本月实际&apos;,colspan:13}], 
        ///[{field: &apos;A00O2TFHXIFF1Z9L44RHTXF07W_F&apos;,title: &apos;结余金额&apos;,sor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0004 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0005_SRV/ZFI_M001_Q0005{0}Results?|Title(0_0)预收帐款统计分析|FrozenColumns(0_0)|Columns(0_0)[[{field: &apos;ZPROFTCTR__ZBU_T&apos;,title: &apos;事业部&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2},{field: &apos;ZPLANT_T&apos;,title: &apos;工厂&apos;,sortable:true, fixed: true,align: &apos;left&apos;,rowspan:2}， {title:&apos;期末余额（本币）&apos;,colspan:9}， {title:&apos;期末余额（美元）&apos;,colspan:3}， {title:&apos;期末余额（欧元）&apos;,colspan:4}，{title:&apos;期末余额（英镑）&apos;,colspan:4}， {title:&apos;期末余额（日元）&apos;,colspan:4}， {title:&apos;累计折合（RMB）&apos;,colspan:1}],        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0005 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0006_SRV/ZFI_M001_Q0006{0}Results?|Title(0_0)往来部份（重分类后）|FrozenColumns(0_0)|Columns(0_0)
        ///[[{title: &apos;债权单位信息&apos;,colspan:2},{title: &apos;债务单位信息&apos;,colspan:2},{title: &apos;债权单位发生额&apos;,colspan:5},{title: &apos;债务单位发生额&apos;,colspan:5}，
        ///{field: &apos;A00O2TFHXIFF1Z9OGYMFIJP3WA_F&apos;,title: &apos;平衡检查&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2}]
        ///,[{ field: &apos;ZCRDTCOMY&apos;,   title: &apos;单位编码&apos;, sortable: true, fixed: true, left: &apos;right&apos; } ，
        ///{ field: &apos;ZCRDTCOMY_T&apos;,   title: &apos;单位名称&apos;, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0006 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0007_SRV/ZFI_M001_Q0007{0}Results?|Title(0_0)关联交易|FrozenColumns(0_0)|Columns(0_0)
        ///[[{title: &apos;销售单位&apos;,colspan:2},{title: &apos;采购单位&apos;,colspan:2},{title: &apos;销售单位发生额&apos;,colspan:3},{title: &apos;采购单位发生额&apos;,colspan:3}，
        ///{field: &apos;A00O2TFHXIFF1Z9OXRJS8XOI3X_F&apos;,title: &apos;本月平衡检查&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2}，
        ///{field: &apos;A00O2TFHXIFF1Z9OXRJS8XOOFH_F&apos;,title: &apos;累计平衡检查&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2}]
        ///,[{ field: &apos;ZCRDTCOMY&apos;,   t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0007 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0008_SRV/ZFI_M001_Q0008{0}Results?|Title(0_0)总体状况概览|FrozenColumns(0_0)|Columns(0_0)
        ///[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;, title:&apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{ field: &apos;ZPLANT_T&apos;,   title: &apos;工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title:&apos;期末余额（本币）&apos;,colspan:9}， {title:&apos;期末余额（美元）&apos;,colspan:3}， {title:&apos;期末余额（欧元）&apos;,colspan:3}，{title:&apos;期末余额（英镑）&apos;,colspan:3}， {title:&apos;期末余额（日元）&apos;,colspan:3}， {title:&apos;累计折合（RMB）&apos;}],        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0008 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0009_SRV/ZFI_M001_Q0009{0}Results?|Title(0_0)按付款方期末余额前五名的应付排行|FrozenColumns(0_0)|Columns(0_0)
        ///[[{field: &apos;ZVENDOR_T&apos;,title: &apos;单位名称&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title: &apos;期末余额&apos;,colspan:2}],
        ///[{field: &apos;A00O2TFHXIFF1Z9P15KV9N553I_F&apos;, title: &apos;应付账款&apos;, sortable: true, fixed: true, align: &apos;right&apos; },
        ///{field: &apos;A00O2TFHXIFF1Z9P15KV9N96HA_F&apos;,title: &apos;占预付账款合计数的比例（%）&apos;, sortable: true, fixed: true, align: &apos;right&apos; }]] 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0009 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0011_SRV/ZFI_M001_Q0011{0}Results?|Title(0_0)总体状况概览|FrozenColumns(0_0)|Columns(0_0)
        ///[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;, title:&apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{ field: &apos;ZPLANT_T&apos;,   title: &apos;工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title:&apos;期末余额（本币）&apos;,colspan:9}， {title:&apos;期末余额（美元）&apos;,colspan:3}， {title:&apos;期末余额（欧元）&apos;,colspan:3}，{title:&apos;期末余额（英镑）&apos;,colspan:3}， {title:&apos;期末余额（日元）&apos;,colspan:3}],
        ///[{ field: &apos;A00O2TFHX [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0011 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0013_SRV/ZFI_M001_Q0013{0}Results?|Title(0_0)对外结构、坏账分析|FrozenColumns(0_0)|Columns(0_0)
        ///[[{field:&apos;ZPROFTCTR__ZSLLTD_T&apos;,title:&apos;双林股司&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:2},{field:&apos;ZPROFTCTR__ZBU_T&apos;,title:&apos;事业部&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:2}
        ///,{field:&apos;ZCOMPCODE_T&apos;,title:&apos;公司代码&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:2},{title: &apos;期初余额&apos;,colspan:3},{title: &apos;本期增加金额&apos;,colspan:2}，{title: &apos;本期增减金额&apos;,colsp [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0013 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0014_SRV/ZFI_M001_Q0014{0}Results?|Title(0_0)量价差异分析|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0014 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZFI_M001_Q0015_SRV/ZFI_M001_Q0015{0}Results?|Title(0_0)按付款方期末余额前五名的预付排行|FrozenColumns(0_0)|Columns(0_0)
        ///[[{field: &apos;ZVENDOR_T&apos;,title: &apos;单位名称&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{title: &apos;期末余额&apos;,colspan:2}],
        ///[{field: &apos;A00O2TFHXIFF3PLPTJZU11CGJX_F&apos;, title: &apos;预付账款&apos;, sortable: true, fixed: true, align: &apos;right&apos; },
        ///{field: &apos;A00O2TFHXIFF3PLPTV10XK7FU0_F&apos;,title: &apos;占预付账款合计数的比例（%）&apos;, sortable: true, fixed: true, align: &apos;right&apos; }]] 的本地化字符串。
        /// </summary>
        public static string TabZFI_M001_Q0015 {
            get {
                return ResourceManager.GetString("TabZFI_M001_Q0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZZFI_P001_Q0001_SRV/ZFI_P001_Q0001{0}Results?|Title(0_0)成本内容|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZFI_P001_Q0001 {
            get {
                return ResourceManager.GetString("TabZFI_P001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0001_SRV/ZMM_M001_Q0001{0}Results?|Title(0_0)|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0001 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0002_SRV/$metadata?|
        ///Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0002_SRV/ZMM_M001_Q0002Results?|Title(0_0)未命名 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0002 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0003_SRV/ZMM_M001_Q0003{0}Results?|Title(0_0)|FrozenColumns(0_0)|Columns(0_0)(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0001_SRV/ZMM_M001_Q0001{0}Results?|Title(0_0)|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0003 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0005_SRV/ZMM_M001_Q0005{0}Results?|Title(0_0)备选指标|FrozenColumns(0_0)|Columns(0_0)[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;, title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{ field: &apos;ZPROFTCTR_T&apos;, title: &apos;生产工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2},{ field: &apos;ZMATPTYPE_T&apos;, title: &apos;存货类别&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2}, {title: &apos;上月库存状况&apos;,colspan:3}, {title: &apos;本月库存状况&apos;,colspan:3}],
        ///[{ field: &apos;A00O2T [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0005 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0006_SRV/ZMM_M001_Q0006{0}Results?|Title(0_0)备选指标|rozenColumns(0_0)|Columns(0_0)[[{field:&apos;ZPROFTCTR__ZBU_T&apos;,title:&apos;事业部&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:3},
        ///{field:&apos;ZPROFTCTR_T&apos;,title:&apos;生产工厂&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:3},
        ///{field:&apos;ZMATPTYPE_T&apos;,title:&apos;存货类别&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:3}，
        /// {title: &apos;年初库存状况&apos;,colspan:2}，{title: &apos;期间库存状况&apos;,colspan:10}]，
        ///[{field:&apos;A00O2TFHXIFF1ZAAFQ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0006 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0007_SRV/ZMM_M001_Q0007{0}Results?|Title(0_0)存货对内结构|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0007 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M001_Q0008_SRV/ZMM_M001_Q0008{0}Results?|Title(0_0)存货账龄|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M001_Q0008 {
            get {
                return ResourceManager.GetString("TabZMM_M001_Q0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0001_SRV/ZMM_M002_Q0001{0}Results?|Title(0_0)总体概况：|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M002_Q0001 {
            get {
                return ResourceManager.GetString("TabZMM_M002_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0002_SRV/ZMM_M002_Q0001{0}Results?|Title(0_0)分库存地点统计：|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M002_Q0002 {
            get {
                return ResourceManager.GetString("TabZMM_M002_Q0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0004_SRV/ZMM_M004_Q0001{0}Results?|Title(0_0)|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZMM_M002_Q0004 {
            get {
                return ResourceManager.GetString("TabZMM_M002_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0001_SRV/ZSD_M001_Q0001{0}Results?|Title(0_0)3年销售汇总趋势|FrozenColumns(0_0)|Columns(0_0)[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;,   title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;ZPLANT_T&apos;,   title: &apos;生产工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;ZDISTCHAN_T&apos;,   title: &apos;销售类型&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;ZSALESDIT_T&apos;,   title: &apos;地域&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZSD_M001_Q0001 {
            get {
                return ResourceManager.GetString("TabZSD_M001_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0004_SRV/ZSD_M001_Q0004{0}Results?|Title(0_0)新品销售贡献分析|FrozenColumns(0_0)|Columns(0_0)[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;,   title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;ZPLANT_T&apos;,   title: &apos;工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;ZCUSTOMER_T&apos;,   title: &apos;客户&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field: &apos;A0MATL_GRP_1_T&apos;,   title: &apos;产品类别&apos;, sortable: true, fixed: true, align: &apos;left&apos; } ，{ field:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZSD_M001_Q0004 {
            get {
                return ResourceManager.GetString("TabZSD_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0006_SRV/ZSD_M001_Q0006{0}Results?|Title(0_0)销售价格变动分析(月报表)|FrozenColumns(0_0)|Columns(0_0)[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;,   title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos;，rowspan:2 } ，{ field: &apos;ZPLANT_T&apos;,   title: &apos;生产工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;，rowspan:2 } ，{ field: &apos;ZDISTCHAN_T&apos;,   title: &apos;销售类型&apos;, sortable: true, fixed: true, align: &apos;left&apos;，rowspan:2 } ，{ field: &apos;ZSALESDIT_T&apos;,   title: &apos;地域&apos;, sortable: true, fixed [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZSD_M001_Q0006 {
            get {
                return ResourceManager.GetString("TabZSD_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M001_Q0013_SRV/ZSD_M001_Q0013{0}Results?|Title(0_0)到期未开票情况分析|FrozenColumns(0_0)|Columns(0_0)[[{ field: &apos;ZPROFTCTR__ZBU_T&apos;,   title: &apos;事业部&apos;, sortable: true, fixed: true, align: &apos;left&apos; ,rowspan:2} ，{ field: &apos;ZPLANT_T&apos;,   title: &apos;工厂&apos;, sortable: true, fixed: true, align: &apos;left&apos;,rowspan:2 } ，{ field: &apos;ZCUSTOMER&apos;,   title: &apos;客户编码&apos;, sortable: true, fixed: true, align: &apos;right&apos;,rowspan:2 } ，{ field: &apos;ZCUSTOMER_T&apos;,   title: &apos;客户名称&apos;, sortable: true, fixed: tru [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZSD_M001_Q0013 {
            get {
                return ResourceManager.GetString("TabZSD_M001_Q0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0006_SRV/ZSD_M002_Q0006{0}Results?|Title(0_0)交期达成概况：|FrozenColumns(0_0)|Columns(0_0) 的本地化字符串。
        /// </summary>
        public static string TabZSD_M002_Q0006 {
            get {
                return ResourceManager.GetString("TabZSD_M002_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZSD_M002_Q0007_SRV/ZSD_M002_Q0007{0}Results?|Title(0_0)延误订单明细分析：|FrozenColumns(0_0)|Columns(0_0)[[{field:&apos;ZPROFTCTR__ZBU_T&apos;,title:&apos;事业部&apos;, sortable: true, fixed: true, align:&apos;left&apos;,},{field:&apos;ZPLANT_T&apos;,title:&apos;工厂&apos;, sortable: true, fixed: true, align:&apos;left&apos;,},{field:&apos;ZCUSTOMER_T&apos;,title:&apos;客户&apos;, sortable: true, fixed: true, align:&apos;left&apos;,},{field:&apos;ZORDDATE_T&apos;,title:&apos;订货日期&apos;, sortable: true, fixed: true, align:&apos;left&apos;,},{field:&apos;ZMATERIAL_T&apos;,title:&apos;物料&apos;, sortable: t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TabZSD_M002_Q0007 {
            get {
                return ResourceManager.GetString("TabZSD_M002_Q0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZMM_M002_Q0001_SRV/ZMM_M002_Q0001{0}Results?|Title(0_0)库存准确率率变化趋势|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PKMY8ZON2VXC3,A00O2TFHXIFF3PKMYCZU7QXJT5|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0) 的本地化字符串。
        /// </summary>
        public static string ZMM_M002_Q0001 {
            get {
                return ResourceManager.GetString("ZMM_M002_Q0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0004_SRV/ZPU_M001_Q0004{0}Results?|Title(0_0)|FrozenColumns(0_0)|Columns(0_0)[[{field:&apos;ZMATERIAL_T&apos;,title:&apos;物料&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:3},{field:&apos;A0MATL_GROUP_T&apos;,title:&apos;物料类别&apos;, sortable: true, fixed: true, align:&apos;left&apos;,rowspan:3},{title:&apos;3&apos;,colspan:7},],[{title:&apos;1&apos;,colspan:4},{title:&apos;2&apos;,colspan:3},],[{field:&apos;A00O2TFHXIFF3PK1SDSSFNT0OI_F&apos;,title:&apos;采购数量&apos;, sortable: true, fixed: true, align:&apos;right&apos;,},{field:&apos;A00O2TFHXIF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ZPU_M001_Q0004 {
            get {
                return ResourceManager.GetString("ZPU_M001_Q0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0005_SRV/ZPU_M001_Q0005{0}Results?|Title(0_0)年度采购价格变动分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PK1T918NI02RV,A00O2TFHXIFF3PK1T918NHZWGB
        ///|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0)A00O2TFHXIFF3PK1T918NI02RV,A00O2TFHXIFF3PK1T918NHZWGB 的本地化字符串。
        /// </summary>
        public static string ZPU_M001_Q0005 {
            get {
                return ResourceManager.GetString("ZPU_M001_Q0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0006_SRV/ZPU_M001_Q0006{0}Results?|Title(0_0)采购降本目标达成分析|FrozenColumns(0_0)|Columns(0_0)[[{field: &apos;ZPROFTCTR__ZBU_T&apos;,title: &apos;事业部&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2},{field: &apos;ZPROFTCTR__ZBU_T&apos;,title: &apos;工厂&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2}，{field: &apos;A0MATL_GROUP&apos;,title: &apos;类别&apos;,sortable:true, fixed: true,align: &apos;right&apos;,rowspan:2}， {title:&apos;月度完成情况&apos;,colspan:6}， {title:&apos;累计完成情况&apos;,colspan:7} ，{title:&apos;上年同期降本情况&apos;,colspan [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ZPU_M001_Q0006 {
            get {
                return ResourceManager.GetString("ZPU_M001_Q0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0007_SRV/ZPU_M001_Q0007{0}Results?|Title(0_0)采购降本月度趋势分析|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PL4CK7IZYJKWW,A00O2TFHXIFF3PL4CK7IZYJR8G,A00O2TFHXIFF3PL4CK7IZYJXK0|AxisDataStr(0_0)A0CALMONTH_T|LegendDataStr(0_0)本年降本,本年降本目标 的本地化字符串。
        /// </summary>
        public static string ZPU_M001_Q0007 {
            get {
                return ResourceManager.GetString("ZPU_M001_Q0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Url(0_0)http://bwdev.shuanglin.com:8000/sap/opu/odata/sap/ZPU_M001_Q0008_SRV/ZPU_M001_Q0008{0}Results?|Title(0_0)供应商降本前十大排行榜|SubTitle(0_0)|SeriesStr(0_0)A00O2TFHXIFF3PL4DAP8R06RZC,A00O2TFHXIFF3PL4DAP8R06YAW|AxisDataStr(0_0)ZVENDOR_T|LegendDataStr(0_0) 的本地化字符串。
        /// </summary>
        public static string ZPU_M001_Q0008 {
            get {
                return ResourceManager.GetString("ZPU_M001_Q0008", resourceCulture);
            }
        }
    }
}
